name: DeployInEc2
on:
    push: 
        branches: 
            - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    environment: production

    steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: SSH into EC2 instance and execute commands
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.EC2_HOST_BACK }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.EC2_PORT }}
            script: |
              sudo docker stop a4ce
              sudo docker start a4ce
              sudo docker exec a4ce /bin/bash -c "cd /home/G5---integrador/BACK\ END && mvn package -DskipTests"
              sudo docker exec a4ce /bin/bash -c "cd /home/G5---integrador/BACK\ END/target && java -jar ProyectoIntegrado-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &"
