name: DeployInEc2
on:
    push: 
        branches: 
            - main
env:
    AWS_REGION: MY_AWS_REGION                   # set this to your preferred AWS region, e.g. us-west-1
    ECR_REPOSITORY: MY_ECR_REPOSITORY           # set this to your Amazon ECR repository name
    ECS_SERVICE: MY_ECS_SERVICE                 # set this to your Amazon ECS service name
    ECS_CLUSTER: MY_ECS_CLUSTER                 # set this to your Amazon ECS cluster name
    ECS_TASK_DEFINITION: MY_ECS_TASK_DEFINITION # set this to the path to your Amazon ECS task definition
                                                    # file, e.g. .aws/task-definition.json
    CONTAINER_NAME: MY_CONTAINER_NAME           # set this to the name of the container in the
                                                    # containerDefinitions section of your task definition
    


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: SSH into EC2 instance and execute commands
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.EC2_PORT }}
            script: |
              sudo docker stop a4ce
              sudo docker start a4ce
              sudo docker exec a4ce /bin/bash -c "cd /home/G5---integrador/BACK END && mvn package -DskipTests"
              sudo docker exec a4ce /bin/bash -c "cd /home/G5---integrador/BACK END/target && java -jar ProyectoIntegrado-0.0.1-SNAPSHOT.jar"
